server:
  port: 8080
spring:
  application:
    name: "accounts"
    profiles:
      active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
      init:
        mode: always
config:
  import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
#      properties:
#        git:
#          branch: ${git.branch:unknown}
#          commit:
#            id: ${git.commit.id:unknown}
#            time: ${git.commit.time:unknown}
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "accounts"
    description: "Wallet-wave Account Application"
    version: "1.0.0"