server:
  port: 9010

spring:
  application:
    name: "message"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: wallet-wave-message-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication
      kafka:
        binder:
          brokers:
            - localhost:9092

wallet-wave:
  kafka:
    topics:
      transaction: transaction-topic            -