name: Wallet-Wave CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build Docker image
        run: docker build -t your-docker-username/walletwave:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push your-docker-username/walletwave:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker stop walletwave || true
            docker rm walletwave || true
            docker rmi your-docker-username/walletwave:latest || true
            docker pull your-docker-username/walletwave:latest
            docker run -d -p 8080:8080 --name walletwave your-docker-username/walletwave:latest
